compilers:
  - compiler:
      spec: clang@18.0.0
      paths:
        cc: /opt/rocm-6.2.4/clang
        cxx: /opt/rocm-6.2.4/clang++
        f77: /opt/rocm-6.2.4/flang
        fc: /opt/rocm-6.2.4/flang
      flags: {}
      operating_system: ubuntu24.04
      target: any
      modules: []
      extra_rpaths: []
      environment: {}
  - compiler:
      spec: gcc@13.3.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortan
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: ubuntu24.04
      target: any
      modules: []
      extra_rpaths: []
      environment: {}
