packages:
  hpcx-mpi:
    require: "@2.18"
    buildable: false
    externals:
      - spec: "hpcx-mpi@2.18"
        prefix: /opt/hpcx-v2.18-gcc-mlnx_ofed-redhat8-cuda12-x86_64/ompi
  slurm:
    buildable: false
    externals:
    - spec: slurm@24.05.4
      prefix: /usr
  mpi:
    require: 'hpcx-mpi'
  all:
    compiler: [gcc@9.2.0]
    variants: build_type=Release
    providers:
      mpi: [hpcx-mpi]
      blas: [openblas]
      lapack: [openblas]
