compilers:
- compiler:
    paths:
      cc: /sw/summit/gcc/12.1.0-0/bin/gcc
      cxx: /sw/summit/gcc/12.1.0-0/bin/g++
      f77: /sw/summit/gcc/12.1.0-0/bin/gfortran
      fc: /sw/summit/gcc/12.1.0-0/bin/gfortran
    operating_system: rhel8
    target: ppc64le
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@12.1.0
