packages:
  all:
    target: [ppc64le]
    compiler:
      - gcc@12.1.0
    providers:
      mpi:
        - spectrum-mpi@10.4
    variants: cuda_arch=70 
  spectrum-mpi:
    version: [10.4]
    buildable: false
    externals:
      - spec: "spectrum-mpi@10.4%gcc@12.1.0"
        modules:
          - spectrum-mpi/10.4.0.6-20230210
  cuda:
    version: [12.2.0]
    buildable: false
    externals:
      - spec: "cuda@12.2.0%gcc"
        modules:
          - cuda/12.2.0
