modules:
  default:
    enable: [tcl]
    roots:
      tcl: $env/modules
    arch_folder: false
    tcl:
      ^mpi:
        environment:
          prepend_path:
            PATH: '{^mpi.prefix}/bin'
      ^amr-wind:
        environment:
          prepend_path:
            PATH: '{^amr-wind.prefix}/bin'
      ^nalu-wind:
        environment:
          prepend_path:
            PATH: '{^nalu-wind.prefix}/bin'
      ^trilinos:
        environment:
          prepend_path:
            PATH: '{^trilinos.prefix}/bin:{^mpi.prefix}/bin'
      ^openfast:
        environment:
          prepend_path:
            PATH: '{^openfast.prefix}/bin'
      projections:
        all: '{name}-{version}/{compiler.name}-{compiler.version}'
        ^openfast: '{^openfast.name}-{^openfast.version}/{name}-{version}/{compiler.name}-{compiler.version}'
      hash_length: 0
      hide_implicits: true
      all:
        autoload: direct
      # just create one module for now
      exclude_implicits: true
