packages:
  ascent:
    variants: ~fortran~openmp
  nalu-wind:
    variants: ~trilinos-solvers
  amr-wind:
    variants: +tiny_profile
  conduit:
    variants: ~fortran~hdf5_compat
  hdf5:
    variants: +cxx+hl
  masa:
    variants: ~fortran~python
  netcdf-c:
    variants: +parallel-netcdf
  parallel-netcdf:
    variants: ~fortran
  tioga:
    version: [develop]
  hypre:
    version: [develop]
    variants: ~fortran
  trilinos:
    variants: ~adios2~amesos~anasazi~aztec~boost~chaco~complex~debug~dtk~epetra~epetraext~float~fortran~hypre~ifpack~intrepid~intrepid2~isorropia~mesquite~minitensor~ml~mumps~nox~openmp~phalanx~piro~python~rol~rythmos~sacado~shylu~stratimikos~suite-sparse~superlu~superlu-dist~teko~tempus~x11
  all:
    variants: build_type=Release
    providers:
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
