packages:
  ascent:
    variants: ~fortran~openmp
  nalu-wind:
    variants: ~trilinos-solvers
  amr-wind:
    variants: +tiny_profile
  conduit:
    variants: ~fortran~hdf5_compat
  hdf5:
    variants: +cxx+hl
  masa:
    variants: ~fortran~python
  netcdf-c:
    variants: +parallel-netcdf
  openfast:
    variants: +cxx
  parallel-netcdf:
    variants: ~fortran
  tioga:
    version: [develop]
  hypre:
    version: [develop]
    variants: ~fortran
  all:
    variants: build_type=Release
    providers:
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
