packages:
  ascent:
    require: "~fortran~openmp"
  exawind:
    require: "@master"
  nalu-wind:
    require: "@master ~trilinos-solvers"
  amr-wind:
    require: "@main +tiny_profile"
  conduit:
    require: "~fortran~hdf5_compat"
  hdf5:
    require: "+cxx+hl"
  masa:
    require: "~fortran~python"
  netcdf-c:
    require: "+parallel-netcdf"
  openfast:
    require: "+cxx"
  parallel-netcdf:
    require: "~fortran"
  tioga:
    require: "@develop"
  hypre:
    require: "@develop ~fortran"
  trilinos:
    require:
      - any_of: ["@=14.1.0.2023.02.28", "@develop"]
  blas:
    require: "netlib-lapack"
  lapack:
    require: "netlib-lapack"
  all:
    require:
      - "build_type=Release"
