compilers:
- compiler:
    spec: gcc@=12.1.0
    paths:
      cc: /projects/aue/cee/builds/x86_64/rhel8/ae2aa8f4/gcc-12.1.0/install/linux-rhel8-x86_64/gcc-10.3.0/gcc-12.1.0-xpyjv5s/bin/gcc
      cxx: /projects/aue/cee/builds/x86_64/rhel8/ae2aa8f4/gcc-12.1.0/install/linux-rhel8-x86_64/gcc-10.3.0/gcc-12.1.0-xpyjv5s/bin/g++
      f77: /projects/aue/cee/builds/x86_64/rhel8/ae2aa8f4/gcc-12.1.0/install/linux-rhel8-x86_64/gcc-10.3.0/gcc-12.1.0-xpyjv5s/bin/gfortran
      fc: /projects/aue/cee/builds/x86_64/rhel8/ae2aa8f4/gcc-12.1.0/install/linux-rhel8-x86_64/gcc-10.3.0/gcc-12.1.0-xpyjv5s/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: [aue/binutils]
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@=2023.2.0
    paths:
      cc: /projects/aue/cee/builds/x86_64/rhel8/e081b0f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-2ixvnj4/compiler/2023.2.0/linux/bin/icx
      cxx: /projects/aue/cee/builds/x86_64/rhel8/e081b0f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-2ixvnj4/compiler/2023.2.0/linux/bin/icpx
      f77: /projects/aue/cee/builds/x86_64/rhel8/e081b0f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-2ixvnj4/compiler/2023.2.0/linux/bin/ifx
      fc: /projects/aue/cee/builds/x86_64/rhel8/e081b0f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-2ixvnj4/compiler/2023.2.0/linux/bin/ifx
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: [aue/binutils, aue/gcc-12.1.0]
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@=16.0.6
    paths:
      cc: /projects/aue/cee/builds/x86_64/rhel8/d00f4910/clang-16.0.6/install/linux-rhel8-x86_64/clang-16.0.6/llvm-16.0.6-f4feo2o/bin/clang
      cxx: /projects/aue/cee/builds/x86_64/rhel8/d00f4910/clang-16.0.6/install/linux-rhel8-x86_64/clang-16.0.6/llvm-16.0.6-f4feo2o/bin/clang++
      f77: /projects/aue/cee/builds/x86_64/rhel8/d00f4910/clang-16.0.6/install/linux-rhel8-x86_64/clang-16.0.6/llvm-16.0.6-f4feo2o/bin/flang-new
      fc: /projects/aue/cee/builds/x86_64/rhel8/d00f4910/clang-16.0.6/install/linux-rhel8-x86_64/clang-16.0.6/llvm-16.0.6-f4feo2o/bin/flang-new
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: [aue/binutils, aue/gcc-12.1.0]
    environment: {}
    extra_rpaths: []
