compilers:
- compiler:
    spec: gcc@=12.1.0
    paths:
      cc: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/gcc-12.1.0/install/linux-rhel7-x86_64/gcc-10.3.0/gcc-12.1.0-6jxiora/bin/gcc
      cxx: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/gcc-12.1.0/install/linux-rhel7-x86_64/gcc-10.3.0/gcc-12.1.0-6jxiora/bin/g++
      f77: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/gcc-12.1.0/install/linux-rhel7-x86_64/gcc-10.3.0/gcc-12.1.0-6jxiora/bin/gfortran
      fc: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/gcc-12.1.0/install/linux-rhel7-x86_64/gcc-10.3.0/gcc-12.1.0-6jxiora/bin/gfortran
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: dpcpp@=2023.2.0
    paths:
      cc: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/icx
      cxx: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/dpcpp
      f77: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/ifx
      fc: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/ifx
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@=2021.10.0
    paths:
      cc: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/intel64/icc
      cxx: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/intel64/icpc
      f77: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/intel64/ifort
      fc: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@=2023.2.0
    paths:
      cc: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/icx
      cxx: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/icpx
      f77: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/ifx
      fc: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/intel-23.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-pvkpgec/compiler/2023.2.0/linux/bin/ifx
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@=16.0.6
    paths:
      cc: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/clang-16.0.6/install/linux-rhel7-x86_64/clang-16.0.6/llvm-16.0.6-fjygaap/bin/clang
      cxx: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/clang-16.0.6/install/linux-rhel7-x86_64/clang-16.0.6/llvm-16.0.6-fjygaap/bin/clang++
      f77: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/gcc-12.1.0/install/linux-rhel7-x86_64/gcc-10.3.0/gcc-12.1.0-6jxiora/bin/gfortran
      fc: /projects/aue/cee/builds/x86_64/rhel7/ba17d7f2/gcc-12.1.0/install/linux-rhel7-x86_64/gcc-10.3.0/gcc-12.1.0-6jxiora/bin/gfortran
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
