spack:
  concretizer:
    unify: false
    reuse: false
  view: false
  specs:
    - exawind~amr_wind_gpu~nalu_wind_gpu~cuda@master %gcc ^nalu-wind+wind-utils+trilinos-solvers@master ^amr-wind+hypre+hdf5+netcdf+masa+waves2amr@main ^tioga@develop
    - exawind~amr_wind_gpu~nalu_wind_gpu~cuda@master %llvm ^nalu-wind+wind-utils+trilinos-solvers@master ^amr-wind+hypre+hdf5+netcdf+masa+waves2amr@main ^tioga@develop
    - exawind~amr_wind_gpu~nalu_wind_gpu~cuda+asan@master build_type=Debug %clang ^nalu-wind+wind-utils+trilinos-solvers+asan@master build_type=Debug ^amr-wind+hypre+hdf5+netcdf+waves2amr+asan@main build_type=Debug ^tioga+asan@develop build_type=Debug ^trilinos+asan build_type=Debug ^hypre+debug
    - exawind+amr_wind_gpu+nalu_wind_gpu+cuda@master cuda_arch=80 %gcc ^nalu-wind~wind-utils~trilinos-solvers@master ^amr-wind+hypre+hdf5+netcdf+waves2amr@main ^tioga@develop
