spack:
  concretizer:
    unify: false
    reuse: false
  view: false
  specs:
  - exawind~amr_wind_gpu~nalu_wind_gpu%clang
  - exawind~amr_wind_gpu~nalu_wind_gpu%gcc
  - exawind+amr_wind_gpu+nalu_wind_gpu%gcc
