spack:
  view: false
  specs:
  - exawind~amr_wind_gpu~nalu_wind_gpu~cuda %gcc ^nalu-wind+wind-utils
  - exawind~amr_wind_gpu~nalu_wind_gpu~cuda %clang ^nalu-wind+wind-utils
    #- exawind~amr_wind_gpu~nalu_wind_gpu~cuda+asan %clang build_type=Debug ^nalu-wind+asan build_type=Debug ^amr-wind+asan build_type=Debug ^tioga+asan build_type=Debug ^trilinos+asan build_type=Debug
    #- exawind+amr_wind_gpu+nalu_wind_gpu+cuda cuda_arch=80 %gcc
