compilers:
  - compiler:
      spec: gcc@12.1.0
      paths:
        cc: /opt/rh/gcc-toolset-12/root/bin/gcc
        cxx: /opt/rh/gcc-toolset-12/root/bin/g++
        f77: /opt/rh/gcc-toolset-12/root/bin/gfortran
        fc: /opt/rh/gcc-toolset-12/root/bin/gfortran
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      extra_rpaths: []
      environment: {}
