packages:
  hypre:
    require: "+shared~fortran"
  mpi:
    require: "mpich"
  blas:
    require: "openblas"
  lapack:
    require: "openblas"
  all:
    require:
      - "%apple-clang"
    variants: build_type=Release
    providers:
      blas: [openblas]
      lapack: [openblas]
