packages:
  trilinos:
    require:
      - "cxxflags='-D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION'"
  nalu-wind:
    require: "cxxflags='-D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION'"
  hypre:
    require: "+shared~fortran"
  mpi:
    require: "mpich"
  blas:
    require: "openblas"
  lapack:
    require: "openblas"
  all:
    require:
      - "%apple-clang"
