packages:
  mpi:
    require: "mpich"
  hypre:
    require: "+shared"
  blas:
    require: "openblas"
  lapack:
    require: "openblas"
  all:
    require:
      - "%apple-clang"
    prefer:
      - "build_type=Release"
