packages:
  mpi:
    require: "mpich"
  blas:
    require: "netlib-lapack"
  lapack:
    require: "netlib-lapack"
  c:
    require: "apple-clang"
  cxx:
    require: "apple-clang"
  fortran:
    require: "gcc"
