compilers:
  - compiler:
      spec: oneapi@2023.2.0
      paths:
        cc: /nopt/nrel/apps/cpu_stack/compilers/06-24/linux-rhel8-sapphirerapids/gcc-12.3.0/intel-oneapi-compilers-2023.2.0-52ic5lt6egfvpfkrr2lxy2lvujpy4ay4/compiler/2023.2.0/linux/bin/icx
        cxx: /nopt/nrel/apps/cpu_stack/compilers/06-24/linux-rhel8-sapphirerapids/gcc-12.3.0/intel-oneapi-compilers-2023.2.0-52ic5lt6egfvpfkrr2lxy2lvujpy4ay4/compiler/2023.2.0/linux/bin/icpx
        f77: /nopt/nrel/apps/cpu_stack/compilers/06-24/linux-rhel8-sapphirerapids/gcc-12.3.0/intel-oneapi-compilers-2023.2.0-52ic5lt6egfvpfkrr2lxy2lvujpy4ay4/compiler/2023.2.0/linux/bin/ifx
        fc: /nopt/nrel/apps/cpu_stack/compilers/06-24/linux-rhel8-sapphirerapids/gcc-12.3.0/intel-oneapi-compilers-2023.2.0-52ic5lt6egfvpfkrr2lxy2lvujpy4ay4/compiler/2023.2.0/linux/bin/ifx
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      extra_rpaths: []
      environment: {}
  - compiler:
      spec: gcc@12.1.0
      paths:
        cc: /opt/rh/gcc-toolset-12/root/bin/gcc
        cxx: /opt/rh/gcc-toolset-12/root/bin/g++
        f77: /opt/rh/gcc-toolset-12/root/bin/gfortran
        fc: /opt/rh/gcc-toolset-12/root/bin/gfortran
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      extra_rpaths: []
      environment: {}
