compilers:
  - compiler:
      spec: oneapi@2023.2.0
      paths:
        cc: /nopt/nrel/apps/cpu_stack/compilers/02-24/spack/opt/spack/linux-rhel8-sapphirerapids/gcc-12.2.1/intel-oneapi-compilers-2023.2.0-hwdq5hei2obxznfjhtlav4mi5h5jd4zw/compiler/2023.2.0/linux/bin/icx
        cxx: /nopt/nrel/apps/cpu_stack/compilers/02-24/spack/opt/spack/linux-rhel8-sapphirerapids/gcc-12.2.1/intel-oneapi-compilers-2023.2.0-hwdq5hei2obxznfjhtlav4mi5h5jd4zw/compiler/2023.2.0/linux/bin/icpx
        f77: /nopt/nrel/apps/cpu_stack/compilers/02-24/spack/opt/spack/linux-rhel8-sapphirerapids/gcc-12.2.1/intel-oneapi-compilers-2023.2.0-hwdq5hei2obxznfjhtlav4mi5h5jd4zw/compiler/2023.2.0/linux/bin/ifx
        fc:  /nopt/nrel/apps/cpu_stack/compilers/02-24/spack/opt/spack/linux-rhel8-sapphirerapids/gcc-12.2.1/intel-oneapi-compilers-2023.2.0-hwdq5hei2obxznfjhtlav4mi5h5jd4zw/compiler/2023.2.0/linux/bin/ifx
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      extra_rpaths:
        - /nopt/nrel/apps/cray-mpich-stall/libs_mpich_nrel_intel
      environment: {}
  - compiler:
      spec: gcc@12.2.0
      paths:
        cc: /opt/cray/pe/gcc/12.2.0/bin/gcc
        cxx: /opt/cray/pe/gcc/12.2.0/bin/g++
        f77: /opt/cray/pe/gcc/12.2.0/bin/gfortran
        fc: /opt/cray/pe/gcc/12.2.0/bin/gfortran
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      extra_rpaths: []
      environment: {}
