compilers:
  - compiler:
      spec: oneapi@2023.2.0
      paths:
        cc: /nopt/nrel/apps/compilers/08-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2023.2.0-cqpelkddr7kvjjmbqgs5ypz27m2bgqgt/compiler/2023.2.0/linux/bin/icx
        cxx: /nopt/nrel/apps/compilers/08-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2023.2.0-cqpelkddr7kvjjmbqgs5ypz27m2bgqgt/compiler/2023.2.0/linux/bin/icpx
        f77: /nopt/nrel/apps/compilers/08-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2023.2.0-cqpelkddr7kvjjmbqgs5ypz27m2bgqgt/compiler/2023.2.0/linux/bin/ifx
        fc: /nopt/nrel/apps/compilers/08-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2023.2.0-cqpelkddr7kvjjmbqgs5ypz27m2bgqgt/compiler/2023.2.0/linux/bin/ifx
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      extra_rpaths: []
      environment: {}
   - compiler:
      spec: gcc@12.2.0
      paths:
        cc: /opt/cray/pe/gcc/12.2.0/bin/gcc
        cxx: /opt/cray/pe/gcc/12.2.0/bin/g++
        f77: /opt/cray/pe/gcc/12.2.0/bin/gfortran
        fc: /opt/cray/pe/gcc/12.2.0/bin/gfortran
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      extra_rpaths: []
      environment: {}
