packages:
  cray-mpich:
    require: "@=8.1.28"
    buildable: false
    externals:
      - spec: "cray-mpich@=8.1.28%oneapi@2023.2.0"
        prefix: /opt/cray/pe/mpich/8.1.28/ofi/intel/2022.1
        modules:
          - libfabric/1.15.2.0
      - spec: "cray-mpich@=8.1.28%gcc@12.1.0"
        prefix: /opt/cray/pe/mpich/8.1.28/ofi/gnu/10.3
        modules:
          - libfabric/1.15.2.0
  cuda:
    require: "@=12.4.1"
  boost:
    require: "@=1.80.0"
  mpi:
    require: "cray-mpich@8.1.28"
  blas:
    require: "openblas"
  lapack:
    require: "openblas"
  all:
    prefer:
      - "%oneapi"
    variants: build_type=Release cuda_arch=90
    providers:
      blas: [openblas]
      lapack: [openblas]
