packages:
  cray-mpich:
    require: "@=8.1.23"
    buildable: false
    externals:
      - spec: "cray-mpich@=8.1.23%oneapi@2023.2.0"
        prefix: /opt/cray/pe/mpich/8.1.23/ofi/intel/19.0
        modules:
          - libfabric/1.15.2.0
  trilinos:
    require:
      - any_of: ["@=14.1.0.2023.02.28", "@develop"]
  nalu-wind:
    variants: ~trilinos-solvers
  openssl:
    version: [1.1.1b]
    buildable: false
    externals:
      - spec: "openssl@1.1.1b%oneapi@2023.2.0"
        prefix: /usr
  mpi:
    require: "cray-mpich@8.1.23"
  blas:
    require: "openblas"
  lapack:
    require: "lapack"
  all:
    require:
      - "%oneapi@2023.2.0"
      - "build_type=Release"
