spack:
  view: false
  specs:
    - 'exawind~amr_wind_gpu~nalu_wind_gpu %oneapi'
      #- 'exawind~amr_wind_gpu~nalu_wind_gpu %gcc'
      #- 'exawind+amr_wind_gpu~nalu_wind_gpu+cuda %gcc'
      #- 'exawind~amr_wind_gpu+nalu_wind_gpu+cuda %gcc'
      #- 'exawind+amr_wind_gpu+nalu_wind_gpu+cuda %gcc'
