spack:
  concretizer:
    unify: false
    reuse: false 
  view: false
  specs:
    - 'exawind+hypre+ninja~amr_wind_gpu~nalu_wind_gpu+fsi %oneapi' #Kestrel CPU
    #- 'exawind+hypre+ninja+amr_wind_gpu+nalu_wind_gpu+fsi+cuda %gcc' #Kestrel GPU
