compilers:
  - compiler:
      spec: oneapi@2024.1
      paths:
        cc: /opt/aurora/23.275.2/CNDA/oneapi/compiler/eng-20231130/bin/icx
        cxx: /opt/aurora/23.275.2/CNDA/oneapi/compiler/eng-20231130/bin/icpx
        f77: /opt/aurora/23.275.2/CNDA/oneapi/compiler/eng-20231130/bin/ifx
        fc: /opt/aurora/23.275.2/CNDA/oneapi/compiler/eng-20231130/bin/ifx
      flags: {}
      operating_system: sles15
      target: x86_64
      modules:
        - oneapi/eng-compiler/2023.12.15.002
        - intel_compute_runtime/release/agama-devel-736.25
      environment: {}
      extra_rpaths: []
