packages:
  mpich:
    require: "@52.2"
    buildable: false
    externals:
      - spec: "mpich@52.2"
        prefix: /opt/aurora/23.275.2/CNDA/mpich/52.2/mpich-ofi-all-icc-default-pmix-gpu-drop52
        modules:
          - mpich/icc-all-pmix-gpu/52.2
          - libfabric/1.15.2.0
  mpi:
    require: "mpich@52.2"
  blas:
    require: "openblas"
  lapack:
    require: "openblas"
  all:
    require:
      - "%oneapi@2024.1"
