packages:
  mpich:
    require: "@20231026"
    buildable: false
    externals:
      - spec: "mpich@20231026"
        prefix: /opt/aurora/24.086.0/CNDA/mpich/20231026/mpich-ofi-all-icc-default-pmix-gpu-drop20231026
        modules:
          - mpich/icc-all-pmix-gpu/20231026
          - libfabric/1.15.2.0
  mpi:
    require: "mpich@20231026"
  all:
    prefer:
      - "%oneapi"
