compilers:
  - compiler:
      spec: clang@17.0.0
      paths:
        cc: /opt/rocm-6.1.3/bin/amdclang
        cxx: /opt/rocm-6.1.3/bin/amdclang++
        f77: /opt/rocm-6.1.3/bin/amdflang
        fc: /opt/rocm-6.1.3/bin/amdflang
      flags: {}
      operating_system: sles15
      target: any
      modules:
        - PrgEnv-amd/8.5.0
        - amd/6.1.3
        - rocm/6.1.3
        - craype-x86-trento
      extra_rpaths: []
      environment: {}
