compilers:
  - compiler:
      spec: clang@17.0.0
      paths:
        cc: /opt/rocm-6.1.3/bin/amdclang
        cxx: /opt/rocm-6.1.3/bin/amdclang++
        f77: /opt/cray/pe/gcc-native/12/bin/gfortran
        fc: /opt/cray/pe/gcc-native/12/bin/gfortran
      flags: {}
      operating_system: sles15
      target: any
      modules:
        - PrgEnv-gnu-amd/8.6.0
        - amd-mixed/6.1.3
        - rocm/6.1.3
        - craype-x86-trento
      extra_rpaths: []
      environment: {}
