spack:
  concretizer:
    unify: false
    reuse: false
  view: false
  specs:
    - 'kynema+amr_wind_gpu+nalu_wind_gpu+rocm'
    - 'kynema+amr_wind_gpu~nalu_wind_gpu+rocm'
    - 'kynema~amr_wind_gpu~nalu_wind_gpu~rocm'
