packages:
  intel-oneapi-compilers:
    externals:
      - spec: intel-oneapi-compilers@2023.2.0
        prefix: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-v3dnk52
        extra_attributes:
          compilers:
            c: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-v3dnk52/compiler/2023.2.0/linux/bin/icx
            cxx: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-v3dnk52/compiler/2023.2.0/linux/bin/icpx
            fortran: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/intel-2023.2.0/install/linux-rhel8-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-v3dnk52/compiler/2023.2.0/linux/bin/ifx
          flags:
            cflags: '-fp-model=precise -fPIC '
            cxxflags: '-fp-model=precise -fPIC '
            fflags: '-fPIC -cpp '
            ldlibs: -lm -lz -ldl
            ldflags: -Wl,--undefined-version
        modules:
        - aue/intel-oneapi-compilers/2023.2.0
  gcc:
    externals:
      - spec: gcc@12.1.0
        prefix: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/gcc-12.1.0/install/linux-rhel8-x86_64/gcc-10.3.0/gcc-12.1.0-xpyjv5s
        extra_attributes:
          compilers:
            c: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/gcc-12.1.0/install/linux-rhel8-x86_64/gcc-10.3.0/gcc-12.1.0-xpyjv5s/bin/gcc
            cxx: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/gcc-12.1.0/install/linux-rhel8-x86_64/gcc-10.3.0/gcc-12.1.0-xpyjv5s/bin/g++
            fortran: /projects/aue/hpc/builds/x86_64/rhel8/ba17d7f2/gcc-12.1.0/install/linux-rhel8-x86_64/gcc-10.3.0/gcc-12.1.0-xpyjv5s/bin/gfortran
          flags:
            cflags: -fPIC
            cxxflags: -fPIC
            fflags: -fPIC -fallow-argument-mismatch
            ldlibs: -lm -lz -ldl
        modules:
        - aue/gcc/12.1.0
  openmpi:
    externals:
    - spec: openmpi@4.1.6+pmi+legacylaunchers+lustre~cuda fabrics=psm2,ofi,verbs schedulers=slurm %oneapi@2023.2.0
      prefix: /projects/aue/hpc/builds/x86_64/rhel8/ompiflux/openmpi-4.1.6-intel-2021.10.0/install/linux-rhel8-x86_64/intel-2021.10.0/openmpi-4.1.6-qdvgpqu
      modules:
      - aue/openmpi/4.1.6-oneapi-2023.2.0
    buildable: false

  boost:
    externals:
    - spec: boost@1.83.0
      prefix: /projects/aue/hpc/builds/x86_64/rhel8/c8f7ebb0/tpls-gcc-12.1.0-openmpi-4.1.6/install/linux-rhel8-x86_64/gcc-12.1.0/boost-1.83.0-em7p3wm
    buildable: false
  perl:
    externals:
    - spec: perl@5.26.3
      prefix: /usr
    buildable: false
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
    buildable: false
  curl:
    externals:
    - spec: curl@7.61.1+ldap
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.1.1k-fips
      prefix: /usr
  python:
    externals:
    - spec: python@3.12.4
      prefix: /projects/aue/hpc/deploy/f9a38d2c/linux-rhel8-x86_64/gcc-12.3.0/python-3.12.4-dln57gx
      modules:
      - aue/python/3.12.4
    buildable: false

  cmake: 
    externals:
    - spec: cmake@3.29.4
      prefix: /projects/aue/hpc/deploy/f9a38d2c/linux-rhel8-x86_64/gcc-12.3.0/cmake-3.29.4-fcknccz
      modules:
      - aue/cmake/3.29.4
    buildable: false 

  parallel-netcdf:
    require: "~fortran"
  netcdf-c:
    require: "+shared build_system=autotools"
  libxml2:
    require: "build_system=autotools"
  mpi:
    require: "openmpi"
  blas:
    require: "netlib-lapack"
  lapack:
    require: "netlib-lapack"
  hdf5:
    require: "~fortran"
  kynema-sgf:
    require: "target=x86_64"
    variants: +tiny_profile
  c:
    prefer:
    - "%oneapi"
  cxx:
    prefer:
    - "%oneapi"
  fortran:
    prefer: 
    - "%oneapi"
  all:
    prefer:
      - "build_type=Release"
      - "target=sapphirerapids"
    conflict:
      - "%gcc"
    permissions:
      write: group
      group: wg-WindHFM
    providers:
      mpi:
      - openmpi
