#!/bin/bash

# Copyright (c) 2022, National Technology & Engineering Solutions of Sandia,
# LLC (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.
#
# This software is released under the BSD 3-clause license. See LICENSE file
# for more details.
#
# Set golds in user config path from spec in current active environment
USER_CONFIGS=${EXAWIND_MANAGER}/configs/user
SPEC=$1
mkdir -p ${USER_CONFIGS}
SPACK_USER_CONFIG_PATH=${USER_CONFIGS} spack config --scope user add "packages:${SPEC}:variants:reference_golds=$(spack location -i ${SPEC})/golds"

