spack:
  concretizer:
    unify: false
    reuse: false 
  view: false
  specs:
    - 'kynema+hypre+kynema_sgf_gpu+kynema_ugf_gpu+cuda cuda_arch=80'
    - 'kynema+hypre~kynema_sgf_gpu~kynema_ugf_gpu~cuda'
    #- 'kynema~hypre+kynema_sgf_gpu~kynema_ugf_gpu+cuda cuda_arch=80 ^kynema-ugf+hypre ^kynema-sgf~hypre'
