spack:
  concretizer:
    unify: false
    reuse: false 
  view: false
  specs:
    - 'kynema+hypre+amr_wind_gpu+nalu_wind_gpu+cuda cuda_arch=80'
    - 'kynema+hypre~amr_wind_gpu~nalu_wind_gpu~cuda'
    #- 'kynema~hypre+amr_wind_gpu~nalu_wind_gpu+cuda cuda_arch=80 ^nalu-wind+hypre ^amr-wind~hypre'
