compilers:
- compiler:
    spec: oneapi@2024.2.1
    paths:
      cc: /glade/u/apps/casper/24.12/spack/opt/spack/intel-oneapi-compilers/2024.2.1/gcc/12.4.0/iq3b/compiler/latest/bin/icx
      cxx: /glade/u/apps/casper/24.12/spack/opt/spack/intel-oneapi-compilers/2024.2.1/gcc/12.4.0/iq3b/compiler/latest/bin/icpx
      f77: /glade/u/apps/casper/24.12/spack/opt/spack/intel-oneapi-compilers/2024.2.1/gcc/12.4.0/iq3b/compiler/latest/bin/ifx
      fc: /glade/u/apps/casper/24.12/spack/opt/spack/intel-oneapi-compilers/2024.2.1/gcc/12.4.0/iq3b/compiler/latest/bin/ifx
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
        NVCC_PREPEND_FLAGS: -allow-unsupported-compiler
        # These are needed for kokkos (see kokkos_check_env.cmake)
        CRAYPE_VERSION: 1
        CRAYPE_LINK_TYPE: dynamic
