compilers:
- compiler:
    spec: intel@2021.10.0
    paths:
      cc: /projects/aue/hpc/builds/x86_64/rhel7/one89362/intel-2023.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-oe6stnz/compiler/2023.2.0/linux/bin/intel64/icc
      cxx: /projects/aue/hpc/builds/x86_64/rhel7/one89362/intel-2023.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-oe6stnz/compiler/2023.2.0/linux/bin/intel64/icpc
      f77: /projects/aue/hpc/builds/x86_64/rhel7/one89362/intel-2023.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-oe6stnz/compiler/2023.2.0/linux/bin/intel64/ifort
      fc: /projects/aue/hpc/builds/x86_64/rhel7/one89362/intel-2023.2.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2023.2.0-oe6stnz/compiler/2023.2.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2021.5.0
    paths:
      cc: /projects/aue/hpc/builds/x86_64/rhel7/one89362/intel-2021.5.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2022.0.2-l3wn3d2/compiler/2022.0.2/linux/bin/intel64/icc
      cxx: /projects/aue/hpc/builds/x86_64/rhel7/one89362/intel-2021.5.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2022.0.2-l3wn3d2/compiler/2022.0.2/linux/bin/intel64/icpc
      f77: /projects/aue/hpc/builds/x86_64/rhel7/one89362/intel-2021.5.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2022.0.2-l3wn3d2/compiler/2022.0.2/linux/bin/intel64/ifort
      fc: /projects/aue/hpc/builds/x86_64/rhel7/one89362/intel-2021.5.0/install/linux-rhel7-x86_64/gcc-10.3.0/intel-oneapi-compilers-2022.0.2-l3wn3d2/compiler/2022.0.2/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@12.1.0
    paths:
      cc: /projects/aue/hpc/builds/x86_64/rhel7/one89362/gcc-12.1.0/install/linux-rhel7-x86_64/gcc-10.3.0/gcc-12.1.0-rplp463/bin/gcc
      cxx: /projects/aue/hpc/builds/x86_64/rhel7/one89362/gcc-12.1.0/install/linux-rhel7-x86_64/gcc-10.3.0/gcc-12.1.0-rplp463/bin/g++
      f77: /projects/aue/hpc/builds/x86_64/rhel7/one89362/gcc-12.1.0/install/linux-rhel7-x86_64/gcc-10.3.0/gcc-12.1.0-rplp463/bin/gfortran
      fc: /projects/aue/hpc/builds/x86_64/rhel7/one89362/gcc-12.1.0/install/linux-rhel7-x86_64/gcc-10.3.0/gcc-12.1.0-rplp463/bin/gfortran
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@10.3.0
    paths:
      cc: /projects/aue/hpc/builds/x86_64/rhel7/one89362/gcc-10.3.0/install/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-tzlyz3c/bin/gcc
      cxx: /projects/aue/hpc/builds/x86_64/rhel7/one89362/gcc-10.3.0/install/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-tzlyz3c/bin/g++
      f77: /projects/aue/hpc/builds/x86_64/rhel7/one89362/gcc-10.3.0/install/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-tzlyz3c/bin/gfortran
      fc: /projects/aue/hpc/builds/x86_64/rhel7/one89362/gcc-10.3.0/install/linux-rhel7-x86_64/gcc-4.8.5/gcc-10.3.0-tzlyz3c/bin/gfortran
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@16.0.6
    paths:
      cc: /projects/aue/hpc/builds/x86_64/rhel7/ba17d7f2/clang-16.0.6/install/linux-rhel7-x86_64/clang-16.0.6/llvm-16.0.6-fjygaap/bin/clang
      cxx: /projects/aue/hpc/builds/x86_64/rhel7/ba17d7f2/clang-16.0.6/install/linux-rhel7-x86_64/clang-16.0.6/llvm-16.0.6-fjygaap/bin/clang++
      f77: /projects/aue/hpc/builds/x86_64/rhel7/ba17d7f2/clang-16.0.6/install/linux-rhel7-x86_64/clang-16.0.6/llvm-16.0.6-fjygaap/bin/flang-new
      fc: /projects/aue/hpc/builds/x86_64/rhel7/ba17d7f2/clang-16.0.6/install/linux-rhel7-x86_64/clang-16.0.6/llvm-16.0.6-fjygaap/bin/flang-new
    flags:
      ldflags: -fuse-ld=lld -L/projects/aue/hpc/builds/x86_64/rhel7/ba17d7f2/clang-16.0.6/install/linux-rhel7-x86_64/clang-16.0.6/llvm-16.0.6-fjygaap/lib
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
