compilers:
- compiler:
  spec: intel@2021.3.0
  paths:
    cc: /projects/global/toss3/compilers/intel/intel_2021/oneapi/compiler/2021.3.0/linux/bin/intel64/icc
    cxx: /projects/global/toss3/compilers/intel/intel_2021/oneapi/compiler/2021.3.0/linux/bin/intel64/icpc
    f77: /projects/global/toss3/compilers/intel/intel_2021/oneapi/compiler/2021.3.0/linux/bin/intel64/ifort
    fc: /projects/global/toss3/compilers/intel/intel_2021/oneapi/compiler/2021.3.0/linux/bin/intel64/ifort
  flags: {}
  operating_system: rhel7
  target: x86_64
  modules: [intel/21.3.0, gnu/7.3.1]
  environment:
    set:
      SPARC_ARCH: cts1-bdw
  extra_rpaths: []

