packages:
  python:
    externals:
    - spec: python@3.11.6+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat+pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
      prefix: /projects/aue/hpc/builds/x86_64/rhel7/54c74814/tooling-sprint-24.02/install/linux-rhel7-x86_64/gcc-10.3.0/python-3.11.6-3lcyd45
  m4:
    externals:
    - spec: m4@1.4.16
      prefix: /usr
  ninja:
    externals:
    - spec: ninja@1.11.1
      prefix: /projects/aue/hpc/builds/x86_64/rhel7/ba17d7f2/tooling/install/linux-rhel7-x86_64/gcc-10.3.0/ninja-1.11.1-iar7zvw
  openmpi:
    externals:
    - spec: openmpi@4.1.6~cuda~cxx~cxx_exceptions~java+lustre~memchecker+pmi~static~wrapper-rpath
        fabrics=ofi,psm,psm2 schedulers=slurm
      prefix: /projects/aue/hpc/builds/x86_64/rhel7/1822dd22/openmpi-4.1.6-intel-2021.5.0/install/linux-rhel7-x86_64/intel-2021.5.0/openmpi-4.1.6-cthhi7m
    buildable: false
  cmake:
    externals:
    - spec: cmake@3.27.7
      prefix: /projects/aue/hpc/builds/x86_64/rhel7/54c74814/tooling-sprint-24.02/install/linux-rhel7-x86_64/gcc-10.3.0/cmake-3.27.7-d7n6dlb
    buildable: false
  curl:
    externals:
    - spec: curl@7.29.0+ldap
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.0.2k-fips
      prefix: /usr
  all:
    permissions:
      read: group
      group: wg-sierra-users
    variants: +mpi build_type=Release
