externals:
  - openssl
  - curl
  - m4
compilers:
  - aue/intel-oneapi-compilers/2023.2.0
modules:
  - module: aue/cmake/3.27.7
    packages: [cmake]
  - module: aue/openmpi/4.1.6-intel-2021.5.0
    packages: [openmpi]
  - module: aue/ninja/1.11.1
    packages: [ninja]
  - module: aue/python/3.11.6
    packages: [python]
