spack:
  view: false
  specs:
  - exawind@master+fsi%oneapi
  - amr-wind@main+openfast
  modules:
    default:
      arch_folder: true
      roots:
        tcl: /projects/wind/modules
  packages:
    all:
      target: [x86_64]
