packages:
  intel-oneapi-compilers:
    externals:
      - spec: intel-oneapi-compilers@2025.0
        prefix: /opt/aurora/24.180.3/updates/oneapi/compiler/eng-20240629
        extra_attributes:
          compilers:
            c: /opt/aurora/24.180.3/updates/oneapi/compiler/eng-20240629/bin/icx
            cxx: /opt/aurora/24.180.3/updates/oneapi/compiler/eng-20240629/bin/icpx
            fortran: /opt/aurora/24.180.3/updates/oneapi/compiler/eng-20240629/bin/ifx
        modules: [oneapi/eng-compiler/2024.07.30.002]
  mpich:
    require: "@4.3.0"
    buildable: false
    externals:
      - spec: "mpich@4.3.0"
        prefix: /opt/aurora/24.180.3/spack/unified/0.8.0/install/linux-sles15-x86_64/oneapi-2024.07.30.002/mpich-4.3.0rc3-fzmrfta
        modules:
          - mpich/opt/4.3.0rc3
          - libfabric/1.20.1
  all:
    providers:
       c: [intel-oneapi-compilers@2025.0]
       cxx: [intel-oneapi-compilers@2025.0]
       fortran: [intel-oneapi-compilers@2025.0]
