packages:
  mpich:
    require: "@20240717"
    buildable: false
    externals:
      - spec: "mpich@20240717"
        prefix: /opt/aurora/24.180.0/CNDA/mpich/20240717/mpich-ofi-all-icc-default-pmix-gpu-drop20240717
        modules:
          - mpich/icc-all-pmix-gpu/20240717
          - libfabric/1.20.1
  exawind:
    require: "@=1.1.0"
  nalu-wind:
    require: "@=2.1.0"
  amr-wind:
    require: "@=3.1.6"
  tioga:
    require: "@=1.2.0"
  hypre:
    require: "@=2.31.0"
  trilinos:
    require: "@=15.1.1"
  openfast:
    require: "@=aurora"
  python:
    require: "@=3.11.9"
  netcdf-c:
    require: "@=4.9.2"
  bzip2:
    require: "@=1.0.8"
  diffutils:
    require: "@=3.10"
  c-blosc:
    require: "@=1.21.5"
  lz4:
    require: "@=1.10.0"
  snappy:
    require: "@=1.2.1"
  libaec:
    require: "@=1.0.6"
  zstd:
    require: "@=1.5.6"
  cmake:
    require: "@=3.30.5"
  curl:
    require: "@=8.8.0"
  nghttp2:
    require: "@=1.63.0"
  openssl:
    require: "@=3.3.1"
  ca-certificates-mozilla:
    require: "@=2023-05-30"
  pkgconf:
    require: "@=2.2.0"
  ncurses:
    require: "@=6.5"
  zlib-ng:
    require: "@=2.2.1"
  gmake:
    require: "@=4.4.1"
  nccmp:
    require: "@=1.9.1.0"
  hdf5:
    require: "@=1.14.5"
  libxml2:
    require: "@=2.10.3"
  libiconv:
    require: "@=1.17"
  xz:
    require: "@=5.4.6"
  netlib-lapack:
    require: "@=3.11.0"
  cgns:
    require: "@=4.4.0"
  hwloc:
    require: "@=2.11.1"
  libpciaccess:
    require: "@=0.17"
  util-macros:
    require: "@=1.20.1"
  kokkos:
    require: "@=4.2.01"
  matio:
    require: "@=1.5.26"
  metis:
    require: "@=5.1.0"
  ninja:
    require: "@=1.12.1"
  expat:
    require: "@=2.6.3"
  libbsd:
    require: "@=0.12.2"
  libmd:
    require: "@=1.0.4"
  gdbm:
    require: "@=1.23"
  gettext:
    require: "@=0.22.5"
  tar:
    require: "@=1.34"
  pigz:
    require: "@=2.8"
  libffi:
    require: "@=3.4.6"
  libxcrypt:
    require: "@=4.4.35"
  readline:
    require: "@=8.2"
  sqlite:
    require: "@=3.46.0"
  util-linux-uuid:
    require: "@=2.40.2"
  re2c:
    require: "@=3.1"
  parallel-netcdf:
    require: "@=1.12.3"
  m4:
    require: "@=1.4.19"
  libsigsegv:
    require: "@=2.14"
  perl:
    require: "@=5.40.0"
  berkeley-db:
    require: "@=18.1.40"
  parmetis:
    require: "@=4.0.3"
  yaml-cpp:
    require: "@=0.6.3"
  mpi:
    require: "mpich@20240717"
  all:
    prefer:
      - "%oneapi@2025.0"
