packages:
  mpich:
    require: "@20240717"
    buildable: false
    externals:
      - spec: "mpich@20240717"
        prefix: /opt/aurora/24.180.0/CNDA/mpich/20240717/mpich-ofi-all-icc-default-pmix-gpu-drop20240717
        modules:
          - mpich/icc-all-pmix-gpu/20240717
          - libfabric/1.20.1
  python:
    require: "@=3.11.9"
  mpi:
    require: "mpich@20240717"
  all:
    prefer:
      - "%oneapi@2025.0"
