packages:
  mpich:
    require: "@52.2"
    buildable: false
    externals:
      - spec: "mpich@52.2"
        prefix: /soft/restricted/CNDA/updates/mpich/52.2/mpich-ofi-all-icc-default-pmix-gpu-drop52
        modules:
          - mpich/52.2/icc-all-pmix-gpu 
          - libfabric/1.15.2.0
  mpi:
    require: "mpich@52.2"
  blas:
    require: "openblas"
  lapack:
    require: "openblas"
  all:
    require:
      - "%oneapi@2024.0"
