packages:
  intel-oneapi-compilers:
    externals:
      - spec: intel-oneapi-compilers@2025.0.5
        prefix: /opt/aurora/24.347.0/oneapi/compiler/latest
        extra_attributes:
          compilers:
            c: /opt/aurora/24.347.0/oneapi/compiler/latest/bin/icx
            cxx: /opt/aurora/24.347.0/oneapi/compiler/latest/bin/icpx
            fortran: /opt/aurora/24.347.0/oneapi/compiler/latest/bin/ifx
        modules: [oneapi/release/2025.0.5]
  gcc:
    externals:
      - spec: gcc@13.3.0
        prefix: /opt/aurora/24.347.0/spack/unified/0.9.2/install/linux-sles15-x86_64/gcc-13.3.0/gcc-13.3.0-4enwbrb
        extra_attributes:
          compilers:
            c: /opt/aurora/24.347.0/spack/unified/0.9.2/install/linux-sles15-x86_64/gcc-13.3.0/gcc-13.3.0-4enwbrb/bin/gcc
            cxx: /opt/aurora/24.347.0/spack/unified/0.9.2/install/linux-sles15-x86_64/gcc-13.3.0/gcc-13.3.0-4enwbrb/bin/g++
            fortran: /opt/aurora/24.347.0/spack/unified/0.9.2/install/linux-sles15-x86_64/gcc-13.3.0/gcc-13.3.0-4enwbrb/bin/gfortran
  mpich:
    require: "@develop"
    buildable: false
    externals:
      - spec: "mpich@develop"
        prefix: /opt/aurora/24.347.0/spack/unified/0.9.2/install/linux-sles15-x86_64/oneapi-2025.0.5/mpich-develop-git.6037a7a-sxnhr7p
        modules:
          - mpich/opt/develop-git.6037a7a
          - libfabric/1.22.0
  c:
    require: "intel-oneapi-compilers@2025.0.5"
  cxx:
    require: "intel-oneapi-compilers@2025.0.5"
  fortran:
    require: "intel-oneapi-compilers@2025.0.5"
  mpi:
    require: "mpich"
  all:
    variants: build_type=Release
