packages:
  mpich:
    require: "@4.3.0"
    buildable: false
    externals:
      - spec: "mpich@4.3.0"
        prefix: /opt/aurora/24.180.3/spack/unified/0.8.0/install/linux-sles15-x86_64/oneapi-2024.07.30.002/mpich-4.3.0rc3-fzmrfta
        modules:
          - mpich/opt/4.3.0rc3
          - libfabric/1.20.1
  all:
    prefer:
      - "%oneapi@2025.0"
