name: Exawind-Manager-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Lint-codespell:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell
      - name: Run codespell
        run: codespell
